/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import { 
  BookOpen, 
  Sparkles, 
  Lightbulb, 
  BrainCircuit,
  Loader2,
  ChevronRight,
  TrendingUp,
  PieChart,
  Target
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export function ResourceHub() {
  const [tips, setTips] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInsights() {
      try {
        const response = await ai.models.generateContent({
          model: "gemini-3-flash-preview",
          contents: "Generate 3 quick, short, practical financial literacy tips for a young professional. Format each tip on a new line and keep them under 20 words each.",
        });
        
        const text = response.text;
        if (text) {
          setTips(text.split('\n').filter(t => t.trim().length > 0));
        }
      } catch (error) {
        console.error("Gemini failed:", error);
        setTips([
          "Build an emergency fund covering 3-6 months of expenses.",
          "Automate your savings to pay yourself first every month.",
          "Diversify your investments to manage risk effectively."
        ]);
      } finally {
        setLoading(false);
      }
    }

    fetchInsights();
  }, []);

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Literacy Hub</h2>
          <p className="text-slate-500 dark:text-slate-400">Expand your knowledge with AI-powered insights and resources.</p>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card className="shadow-sm border-primary/10 bg-primary/5">
          <CardHeader>
            <div className="flex items-center gap-2 text-primary mb-2">
              <Sparkles className="w-5 h-5" />
              <Badge variant="outline" className="text-primary border-primary">AI Insights</Badge>
            </div>
            <CardTitle>Daily Financial Wisdom</CardTitle>
            <CardDescription>Bite-sized tips generated by Gemini to improve your financial health.</CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center gap-2 text-slate-400 py-4">
                <Loader2 className="w-4 h-4 animate-spin" />
                Thinking...
              </div>
            ) : (
              <ul className="space-y-4">
                {tips.map((tip, i) => (
                  <li key={i} className="flex gap-3 p-3 bg-white/80 dark:bg-slate-900/50 rounded-lg border border-primary/5 shadow-sm">
                    <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center shrink-0">
                      <Lightbulb className="w-4 h-4 text-primary" />
                    </div>
                    <p className="text-sm font-medium text-slate-700 dark:text-slate-200">{tip}</p>
                  </li>
                ))}
              </ul>
            )}
            <Button variant="link" className="text-primary p-0 mt-4 h-auto">Get more insights <ChevronRight className="w-4 h-4" /></Button>
          </CardContent>
        </Card>

        <Card className="shadow-sm border-slate-200">
          <CardHeader>
            <CardTitle>Learning Tracks</CardTitle>
            <CardDescription>Curated guides for your financial journey.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {[
              { title: 'Investing for Beginners', duration: '15 min read', icon: TrendingUp },
              { title: 'Mastering the 50/30/20 Rule', duration: '10 min read', icon: PieChart },
              { title: 'Understanding Compound Interest', duration: '12 min read', icon: BrainCircuit },
            ].map((track, i) => (
              <div key={i} className="flex items-center justify-between p-4 rounded-xl border border-slate-100 hover:border-primary/20 hover:bg-slate-50 transition-all cursor-pointer group">
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-lg bg-slate-100 flex items-center justify-center text-slate-500 group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                    <track.icon className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="font-semibold text-slate-900">{track.title}</div>
                    <div className="text-xs text-slate-500">{track.duration}</div>
                  </div>
                </div>
                <ChevronRight className="w-5 h-5 text-slate-300 group-hover:text-primary transition-colors" />
              </div>
            ))}
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
         <Card className="shadow-sm">
            <CardHeader>
               <BookOpen className="w-8 h-8 text-indigo-500 mb-2" />
               <CardTitle className="text-lg">Budgeting Basics</CardTitle>
            </CardHeader>
            <CardContent>
               <p className="text-sm text-slate-500 leading-relaxed">
                  Learn how to set up a budget that works for you, using the envelope method or digital tools.
               </p>
            </CardContent>
         </Card>
         <Card className="shadow-sm">
            <CardHeader>
               <TrendingUp className="w-8 h-8 text-green-500 mb-2" />
               <CardTitle className="text-lg">Investment Types</CardTitle>
            </CardHeader>
            <CardContent>
               <p className="text-sm text-slate-500 leading-relaxed">
                  Stocks, bonds, mutual funds, and ETFs. Understand the difference before you put your money down.
               </p>
            </CardContent>
         </Card>
         <Card className="shadow-sm">
            <CardHeader>
               <Target className="w-8 h-8 text-orange-500 mb-2" />
               <CardTitle className="text-lg">Debt Management</CardTitle>
            </CardHeader>
            <CardContent>
               <p className="text-sm text-slate-500 leading-relaxed">
                  Techniques for paying off debt efficiently including the Snowball and Avalanche methods.
               </p>
            </CardContent>
         </Card>
      </div>
    </div>
  );
}
